import { NotionBlock } from "./NotionBlock.enum";

export const HumanFriendlyBlockName = {
  [NotionBlock.BOOKMARK]: "Bookmark",
  [NotionBlock.BREADCRUMB]: "Breadcrumb",
  [NotionBlock.BULLETED_LIST_ITEM]: "Bulleted List Item",
  [NotionBlock.CALLOUT]: "Callout",
  [NotionBlock.CHILD_DATABASE]: "Child Database",
  [NotionBlock.CHILD_PAGE]: "Child Page",
  [NotionBlock.CODE]: "Code",
  [NotionBlock.COLUMN]: "Column",
  [NotionBlock.COLUMN_LIST]: "Column List",
  [NotionBlock.DIVIDER]: "Divider",
  [NotionBlock.EMBED]: "Embed",
  [NotionBlock.EQUATION]: "Equation",
  [NotionBlock.FILE]: "File",
  [NotionBlock.HEADING_1]: "Heading 1",
  [NotionBlock.HEADING_2]: "Heading 2",
  [NotionBlock.HEADING_3]: "Heading 3",
  [NotionBlock.IMAGE]: "Image",
  [NotionBlock.LINK_PREVIEW]: "Link Preview",
  [NotionBlock.LINK_TO_PAGE]: "Link to Page",
  [NotionBlock.NUMBERED_LIST_ITEM]: "Numbered List Item",
  [NotionBlock.PARAGRAPH]: "Paragraph",
  [NotionBlock.PDF]: "PDF",
  [NotionBlock.QUOTE]: "Quote",
  [NotionBlock.SYNCED_BLOCK]: "Synced Block",
  [NotionBlock.TABLE]: "Table",
  [NotionBlock.TABLE_OF_CONTENTS]: "Table of Contents",
  [NotionBlock.TABLE_ROW]: "Table Row",
  [NotionBlock.TEMPLATE]: "Template",
  [NotionBlock.TO_DO]: "To-do",
  [NotionBlock.TOGGLE]: "Toggle",
  [NotionBlock.UNSUPPORTED]: "Unsupported",
  [NotionBlock.VIDEO]: "Video",
};
